### ISSUE TITLE
Packaging surfvis

### ISSUE THREAD

**Issue by bennahugo** [ratt-ru/surfvis#1]
I find this quite a useful little tool. @IanHeywood do you mind if I package it, so we can put it on pypi?

The idea is to use this in combination with @sjperkins' tricolour flagger

**Comment by IanHeywood** [comment]
Totally fine with me. Please feel free to modify it as you see fit, or just harvest the bits that you need.

Cheers.

**Comment by landmanbester** [comment]
Well this is handy. I py3ified the print statements and added a setup.py [here](https://github.com/landmanbester/surfvis/tree/py3). Seems to install and run through just fine. I might add a few features. Let me know if you want me to submit a PR @IanHeywood

**Comment by IanHeywood** [comment]
Thanks, please go for it.

**Comment by IanHeywood** [comment]
I've added you as a collaborator @landmanbester

**Comment by landmanbester** [comment]
I've just put out a pre-release so closing this one for now. Please reopen if you run into issues
